### PR TITLE
More mousebinding support

### PR DESCRIPTION
**Pull request by ARDiDo**
This will add support for the iconify, maximize, and close mouse contexts, as well as for the press, click, release, and double click (already supported) mouse events.
I moved the default actions of the iconify, maximize, and close buttons to click mouse bindings. This felt more natural to me.
I also changed up the formatting of labwc-config(5) a bit because `'TitleBar'` wouldn't display with mandoc's or busybox's man commands. I'm not sure if this is the case for man-db's man.

### CODE REVIEW

**Comment by johanmalm** [comment]
Ta

**Comment by johanmalm** [comment]
@ARDiDo Is there a way we could chat offline? Maybe e-mail?

**Comment by ARDiDo** [comment]
Email works for me @johanmalm. I could email you using my preferred email, or I could change my commit email address to it. Whatever works best for you.

**Comment by johanmalm** [comment]
@ARDiDo that would be good. Maybe if you e-mail me that would be easiest.

**Pull request merged**
