### PR TITLE
Scene SSD

### PR DESCRIPTION
**Pull request by Consolatis**
SSD test implementation for xdg and xwayland based on your branch.
Maybe all parts of the SSD should be put into yet another treenode so its easier to disable all of the SSD including borders.

`desktop_surface_and_view_at` is updated as well to set the correct `enum ssd_part_type` so dragging the window and button presses work.

Cleanup and updating geometry on surface size change is missing completely.

Just for discussion / inspiration.

scene_ssd_draft

### CODE REVIEW

**Comment by johanmalm** [comment]
Great effort.

> Maybe all parts of the SSD should be put into yet another treenode so its easier to disable all of the SSD including borders.

Yes, good idea. It would be good to keep in mind `<theme><keepBorder>yes|no</keepBorder></theme>`. It not yet implemented, but it's a nice feature whereby a user to keep the border even if the rest of the window decoration is turned off. It might be a reason to design a separate treenode for the border compared with the titlebar, buttons, etc.

http://openbox.org/wiki/Help:Configuration

> `desktop_surface_and_view_at` is updated as well to set the correct `enum ssd_part_type` so dragging the window and button presses work.

Nice.

A couple of additional thoughts.... I'm sure you're already thinking these, but just putting them down anyway.

1. Include output->scale to support HiDPI setups
2. Where do we use rects vs buffers. For example for top rounded corners, buttons, buttons.
3. Regarding `surface_at`, positioning and rendering the ssd, I think we're always going to need a notion of a visible part and an invisible part. For example, to allow a "resize-grab" area that's wider than a thin border at say 1px, we need an invisible border at say 8px. It's the same with buttons; we want a clickable area which is generally a bit bigger than the actual image itself. Not sure how best best structure that in terms of nodes... maybe a hierarchy where the invisible area sits above the visible area makes sense.
4. The dreaded case of the resize-grab area above layer-shell exclusive areas (like the panel). So maybe that's a good reason to have the invisible area be positioned outside the borders/titlebars so that they can be disabled when intersecting with layer-exclusive areas (haven't really thought that through.. just thinking high-level conceptual)
5. Careful with the word `close` as variable/function. Might get odd behaviour if unistd.h included with close(2)

**Comment by johanmalm** [comment]
@Consolatis not sure if you get a notification on a branch like this, so just doing this as a ping :smile:

**Comment by Consolatis** [comment]
Hooray for dump feature. This is what it looks like with a single foot terminal open + SSD:
```
:: view_tree ::
tree (0,0) [0xaaaaaabe31b0]
   +-- tree (1186,134) [0xaaaaaad821a0] <-- view->scene_tree
      +-- tree (1186,134) [0xaaaaaad8d960]
         +-- tree (1186,134) [0xaaaaaad8dab0]
            +-- surface (1186,134) [0xaaaaaad8db10]
      +-- tree (1186,134) [0xaaaaaada2910] <-- view->scene_ssd.all
         +-- tree (1163,88) [0xaaaaaada2970] <-- view->scene_ssd.extends.all
            +-- rect (1163,88) [0xaaaaaad8dd70]
            +-- rect (1183,88) [0xaaaaaada29d0]
            +-- rect (1889,88) [0xaaaaaada2a50]
            +-- rect (1163,108) [0xaaaaaada2ad0]
            +-- rect (1889,108) [0xaaaaaada2b50]
            +-- rect (1163,637) [0xaaaaaada2bd0]
            +-- rect (1183,637) [0xaaaaaada2c50]
            +-- rect (1889,637) [0xaaaaaada2cd0]
         +-- tree (1183,134) [0xaaaaaabbfa50] <-- view->scene_ssd.border.all
            +-- rect (1183,134) [0xaaaaaae79100]
            +-- rect (1886,134) [0xaaaaaada2ff0]
            +-- rect (1183,634) [0xaaaaaada3070]
         +-- tree (1183,108) [0xaaaaaada30f0] <-- view->scene_ssd.titlebar.all
            +-- rect (1209,108) [0xaaaaaada3150]
            +-- rect (1183,108) [0xaaaaaada31d0]
            +-- rect (1811,108) [0xaaaaaada3250]
            +-- rect (1837,108) [0xaaaaaada32d0]
            +-- rect (1863,108) [0xaaaaaada3350]
:: osd_tree ::
```

**Comment by johanmalm** [comment]
Looking good!

**Comment by Consolatis** [comment]
Current state:
ssd_theme_colors

In dcc932733cf088ead19c6a1c91beb1c14a54bef6 I added a wrapper to create a font buffer instead of a texture. Not sure its the right way to do it though. Also I am not sure if freeing buffer->data is correct but I didn't see any free() calls for ->data in the destroy handler of src/buffer.c. If drop_buffer is called and there are other users it just copies and then assigns the copy to ->data thus to me it looks like its leaking the original data pointer at that point. Thus I tried to work around it.

**Comment by johanmalm** [comment]
Yeah, not sure. I'll try to reach out on the sway-devel on IRC to see if anyone can spare some time to guide us on wlr_buffers

**Comment by Consolatis** [comment]
ssd_full_width

```
:: view_tree ::
tree (0,0) [0xaaaaaabe5770]
   +-- tree (1186,134) [0xaaaaaada1c50]
      +-- tree (1186,134) [0xaaaaaada1d50] <-- client_surface
         +-- tree (1186,134) [0xaaaaaada1ea0]
            +-- surface (1186,134) [0xaaaaaada1f00]
      +-- tree (1186,134) [0xaaaaaada2450] <-- ssd
         +-- tree (1165,88) [0xaaaaaada24b0] <-- invisble resize extends
            +-- rect (1165,88) [0xaaaaaabc53a0]
            +-- rect (1185,88) [0xaaaaaabbb900]
            +-- rect (1887,88) [0xaaaaaae82ab0]
            +-- rect (1165,108) [0xaaaaaada2510]
            +-- rect (1887,108) [0xaaaaaada2590]
            +-- rect (1165,635) [0xaaaaaad8bf90]
            +-- rect (1185,635) [0xaaaaaad8c010]
            +-- rect (1887,635) [0xaaaaaad8c090]
         +-- tree (1185,134) [0xaaaaaabbad10] <-- border
            +-- rect (1185,134) [0xaaaaaad8c3b0]
            +-- rect (1886,134) [0xaaaaaad8c430]
            +-- rect (1185,634) [0xaaaaaad8c4b0]
         +-- tree (1185,108) [0xaaaaaad8c530] <-- titlebar
            +-- rect (1185,108) [0xaaaaaad8c590]
               +-- buffer (1547,112) [0xaaaaaadac6f0] <-- title
            +-- rect (1185,108) [0xaaaaaad8cb20] <-- button
               +-- buffer (1195,118) [0xaaaaaad8cba0]
            +-- rect (1809,108) [0xaaaaaad8cc50]
               +-- buffer (1818,117) [0xaaaaaad8ccd0]
            +-- rect (1835,108) [0xaaaaaad8cd80]
               +-- buffer (1844,117) [0xaaaaaad8ce00]
            +-- rect (1861,108) [0xaaaaaad8ceb0]
               +-- buffer (1870,117) [0xaaaaaad8cf30]
:: osd_tree ::
```

Still lots of old code to remove / clean up. I don't really like those massive creations of scene nodes in ({extends,border,top}_{create,update,destroy}) either. Maybe should be converted into the old `struct ssd_part` design.

Just based on the functionality I like it though, its still missing the button hover effects + different buffers for active/inactive + rounded corners.

Edit:
> Still lots of old code to remove / clean up.
> Maybe should be converted into the old `struct ssd_part` design.

Been there. Done that.

**Comment by Consolatis** [comment]
Time for an update:
ssd_hover
Button hover is implemented, same for rounded corners.

```
:: view_tree ::
tree (0,0) [0xaaaaaabe4770]
   +-- tree (1186,134) [0xaaaaaae81310]
      +-- tree (1186,134) [0xaaaaaadabe30]
         +-- tree (1186,134) [0xaaaaaadabf80]
            +-- surface (1186,134) [0xaaaaaada4a40]
      +-- tree (1186,134) [0xaaaaaada4f90] <-- whole ssd
         +-- tree (1165,88) [0xaaaaaada4ff0] <-- insible extends
            +-- rect (1165,88) [0xaaaaaabba900]
            +-- rect (1185,88) [0xaaaaaabc43a0]
            +-- rect (1887,88) [0xaaaaaada5050]
            +-- rect (1165,108) [0xaaaaaada50d0]
            +-- rect (1887,108) [0xaaaaaada5250]
            +-- rect (1165,635) [0xaaaaaada5310]
            +-- rect (1185,635) [0xaaaaaada53d0]
            +-- rect (1887,635) [0xaaaaaada5490]
         +-- tree (1185,134) [0xaaaaaada51b0] <-- borders
            +-- rect (1185,134) [0xaaaaaada5550]
            +-- rect (1886,134) [0xaaaaaada5610]
            +-- rect (1185,634) [0xaaaaaada56d0]
         +-- tree (1185,108) [0xaaaaaada5750] <-- titlebar
            +-- rect (1211,108) [0xaaaaaada57f0] <-- title background
               +-- buffer (1521,112) [0xaaaaaada5d10] <-- title
            +-- buffer (1185,108) [0xaaaaaada5e00] <-- corner_button
               +-- buffer (1195,118) [0xaaaaaada5ef0] <-- icon
               +-- rect (1185,108) [0xaaaaaada5fe0] <-- hover overlay
            +-- rect (1809,108) [0xaaaaaada60a0] <-- normal button
               +-- buffer (1818,117) [0xaaaaaada6160]
               +-- rect (1809,108) [0xaaaaaada6250]
            +-- rect (1835,108) [0xaaaaaada6310]
               +-- buffer (1844,117) [0xaaaaaada63d0]
               +-- rect (1835,108) [0xaaaaaad8ff50]
            +-- buffer (1861,108) [0xaaaaaad90010]
               +-- buffer (1870,117) [0xaaaaaad90100]
               +-- rect (1861,108) [0xaaaaaad901f0]
:: osd_tree ::
```

Active / Inactive is still missing + `theme.c` `xbm.c` and `font.c` need some cleanup.
`BUTTON_WIDTH` and `SSD_HEIGHT` are still hardcoded defines in `include/ssd.h`, will change the callers to use `theme` based ones.
`ssd.c` was split up into 5 files and moved to src/ssd: `ssd.c` `ssd_part.c` `ssd_titlebar.c` `ssd_border.c` `ssd_extends.c`.

Should I remove all the `wlr_texture` based functions completely?
I left them in as wrappers around the shared `_generate_pixel_data` functions so they can be used for `lab_data_buffer` and `wlr_texture`. If scene-graph is indeed intended to be used with opaque render backends and doesn't provide a way to import `wlr_texture`s I guess it would make sense to get rid of them.

**Comment by johanmalm** [comment]
> ```
> :: view_tree ::
> tree (0,0) [0xaaaaaabe4770]
>    +-- tree (1186,134) [0xaaaaaae81310]
>       +-- tree (1186,134) [0xaaaaaadabe30]
>          +-- tree (1186,134) [0xaaaaaadabf80]
>             +-- surface (1186,134) [0xaaaaaada4a40]
>       +-- tree (1186,134) [0xaaaaaada4f90] <-- whole ssd
>          +-- tree (1165,88) [0xaaaaaada4ff0] <-- insible extends
>             +-- rect (1165,88) [0xaaaaaabba900]
>             +-- rect (1185,88) [0xaaaaaabc43a0]
>             +-- rect (1887,88) [0xaaaaaada5050]
>             +-- rect (1165,108) [0xaaaaaada50d0]
>             +-- rect (1887,108) [0xaaaaaada5250]
>             +-- rect (1165,635) [0xaaaaaada5310]
>             +-- rect (1185,635) [0xaaaaaada53d0]
>             +-- rect (1887,635) [0xaaaaaada5490]
>          +-- tree (1185,134) [0xaaaaaada51b0] <-- borders
>             +-- rect (1185,134) [0xaaaaaada5550]
>             +-- rect (1886,134) [0xaaaaaada5610]
>             +-- rect (1185,634) [0xaaaaaada56d0]
>          +-- tree (1185,108) [0xaaaaaada5750] <-- titlebar
>             +-- rect (1211,108) [0xaaaaaada57f0] <-- title background
>                +-- buffer (1521,112) [0xaaaaaada5d10] <-- title
>             +-- buffer (1185,108) [0xaaaaaada5e00] <-- corner_button
>                +-- buffer (1195,118) [0xaaaaaada5ef0] <-- icon
>                +-- rect (1185,108) [0xaaaaaada5fe0] <-- hover overlay
>             +-- rect (1809,108) [0xaaaaaada60a0] <-- normal button
>                +-- buffer (1818,117) [0xaaaaaada6160]
>                +-- rect (1809,108) [0xaaaaaada6250]
>             +-- rect (1835,108) [0xaaaaaada6310]
>                +-- buffer (1844,117) [0xaaaaaada63d0]
>                +-- rect (1835,108) [0xaaaaaad8ff50]
>             +-- buffer (1861,108) [0xaaaaaad90010]
>                +-- buffer (1870,117) [0xaaaaaad90100]
>                +-- rect (1861,108) [0xaaaaaad901f0]
> :: osd_tree ::
> ```

Looking good.

> Should I remove all the `wlr_texture` based functions completely?

yes, definitely

**Comment by johanmalm** [comment]
```
src/ssd/ssd_part.c:1: WARNING: Improper SPDX comment style for 'src/ssd/ssd_part.c', please use '//' instead
src/ssd/ssd_part.c:1: WARNING: Missing or malformed SPDX-License-Identifier tag in line 1
src/ssd/ssd_titlebar.c:1: WARNING: Improper SPDX comment style for 'src/ssd/ssd_titlebar.c', please use '//' instead
src/ssd/ssd_titlebar.c:1: WARNING: Missing or malformed SPDX-License-Identifier tag in line 1
src/ssd/ssd_titlebar.c:231: ERROR: trailing statements should be on next line
	- There is a weird semi-colon after the open brace
src/ssd/ssd_titlebar.c:255: WARNING: Prefer using '"%s...", __func__' to using 'ssd_button_hover_enable', this function's name, in a string
	- Also no need to add 'Warning'. It's obvious being a WLR_ERROR 
src/ssd/ssd_border.c:1: WARNING: Improper SPDX comment style for 'src/ssd/ssd_border.c', please use '//' instead
src/ssd/ssd_border.c:1: WARNING: Missing or malformed SPDX-License-Identifier tag in line 1
src/ssd/ssd_border.c:61: ERROR: space required before the open parenthesis '('
src/ssd/ssd.c:1: WARNING: Improper SPDX comment style for 'src/ssd/ssd.c', please use '//' instead
src/ssd/ssd.c:1: WARNING: Missing or malformed SPDX-License-Identifier tag in line 1
src/ssd/ssd.c:177: ERROR: open brace '{' following function definitions go on the next line
src/ssd/ssd.c:268: WARNING: Prefer using '"%s...", __func__' to using 'ssd_set_active', this function's name, in a string
src/ssd/ssd_extents.c:1: WARNING: Improper SPDX comment style for 'src/ssd/ssd_extents.c', please use '//' instead
src/ssd/ssd_extents.c:1: WARNING: Missing or malformed SPDX-License-Identifier tag in line 1
include/ssd.h:17: ERROR: space required before the open parenthesis '('
include/ssd.h:19: ERROR: Macros with complex values should be enclosed in parentheses
```

**Comment by johanmalm** [comment]
```
src/ssd/ssd_part.c:1: WARNING: Improper SPDX comment style for 'src/ssd/ssd_part.c', please use '//' instead
src/ssd/ssd_part.c:1: WARNING: Missing or malformed SPDX-License-Identifier tag in line 1
src/ssd/ssd_titlebar.c:1: WARNING: Improper SPDX comment style for 'src/ssd/ssd_titlebar.c', please use '//' instead
src/ssd/ssd_titlebar.c:1: WARNING: Missing or malformed SPDX-License-Identifier tag in line 1
src/ssd/ssd_titlebar.c:237: ERROR: trailing statements should be on next line
src/ssd/ssd_titlebar.c:264: WARNING: Prefer using '"%s...", __func__' to using 'ssd_button_hover_enable', this function's name, in a string
src/ssd/ssd_border.c:1: WARNING: Improper SPDX comment style for 'src/ssd/ssd_border.c', please use '//' instead
src/ssd/ssd_border.c:1: WARNING: Missing or malformed SPDX-License-Identifier tag in line 1
src/ssd/ssd_border.c:61: ERROR: space required before the open parenthesis '('
src/ssd/ssd.c:1: WARNING: Improper SPDX comment style for 'src/ssd/ssd.c', please use '//' instead
src/ssd/ssd.c:1: WARNING: Missing or malformed SPDX-License-Identifier tag in line 1
src/ssd/ssd.c:177: ERROR: open brace '{' following function definitions go on the next line
src/ssd/ssd.c:268: WARNING: Prefer using '"%s...", __func__' to using 'ssd_set_active', this function's name, in a string
src/ssd/ssd_extents.c:1: WARNING: Improper SPDX comment style for 'src/ssd/ssd_extents.c', please use '//' instead
src/ssd/ssd_extents.c:1: WARNING: Missing or malformed SPDX-License-Identifier tag in line 1
src/common/scene-helpers.c:1: WARNING: Improper SPDX comment style for 'src/common/scene-helpers.c', please use '//' instead
src/common/scene-helpers.c:1: WARNING: Missing or malformed SPDX-License-Identifier tag in line 1
src/menu/menu.c:162: WARNING: quoted string split across lines
src/menu/menu.c:168: WARNING: quoted string split across lines
src/menu/menu.c:522: WARNING: Prefer using '"%s...", __func__' to using 'menu_process_cursor_motion', this function's name, in a string
include/ssd.h:17: ERROR: space required before the open parenthesis '('
include/ssd.h:19: ERROR: Macros with complex values should be enclosed in parentheses
```

**Comment by johanmalm** [comment]
20220220_20h18m36s_grim

Looking good except the top border - but let's work on that later :smile:

**Comment by johanmalm** [comment]
```
src/common/scene-helpers.c:1: WARNING: Improper SPDX comment style for 'src/common/scene-helpers.c', please use '//' instead
src/common/scene-helpers.c:1: WARNING: Missing or malformed SPDX-License-Identifier tag in line 1
src/menu/menu.c:162: WARNING: quoted string split across lines
src/menu/menu.c:168: WARNING: quoted string split across lines
src/menu/menu.c:522: WARNING: Prefer using '"%s...", __func__' to using 'menu_process_cursor_motion', this function's name, in a string
```

**Comment by johanmalm** [comment]
```
==9392==ERROR: AddressSanitizer: stack-buffer-overflow on address 0x7ffe05a3c800 at pc 0x5573bb767ad4 bp 0x7ffe05a3c770 sp 0x7ffe05a3c760
READ of size 8 at 0x7ffe05a3c800 thread T0
    #0 0x5573bb767ad3 in ssd_border_create ../src/ssd/ssd_border.c:24
    #1 0x5573bb75dd0b in ssd_create ../src/ssd/ssd.c:145
    #2 0x5573bb73d961 in map ../src/xwayland.c:277
    #3 0x5573bb739be8 in handle_map ../src/xwayland.c:67
    #4 0x5573bb95efda in wlr_signal_emit_safe ../subprojects/wlroots/util/signal.c:29
    #5 0x5573bb978885 in xwayland_surface_role_commit ../subprojects/wlroots/xwayland/xwm.c:849
    #6 0x5573bb8c66fd in surface_commit_state ../subprojects/wlroots/types/wlr_compositor.c:466
    #7 0x5573bb8c78bb in surface_handle_commit ../subprojects/wlroots/types/wlr_compositor.c:523
    #8 0x7fa797da1d49  (/usr/lib/libffi.so.8+0x6d49)
    #9 0x7fa797da1266  (/usr/lib/libffi.so.8+0x6266)
    #10 0x7fa79940d322  (/usr/lib/libwayland-server.so.0+0xd322)
    #11 0x7fa7994085cb  (/usr/lib/libwayland-server.so.0+0x85cb)
    #12 0x7fa79940b1c9 in wl_event_loop_dispatch (/usr/lib/libwayland-server.so.0+0xb1c9)
    #13 0x7fa799408d36 in wl_display_run (/usr/lib/libwayland-server.so.0+0x8d36)
    #14 0x5573bb70bdc5 in main ../src/main.c:82
    #15 0x7fa79801730f in __libc_start_call_main (/usr/lib/libc.so.6+0x2d30f)
    #16 0x7fa7980173c0 in __libc_start_main@GLIBC_2.2.5 (/usr/lib/libc.so.6+0x2d3c0)
    #17 0x5573bb6ea594 in _start (/home/johan/tmp/labwc-Consolatis/build/labwc+0x48a594)
```

**Comment by johanmalm** [comment]
```
../src/ssd/ssd_titlebar.c:242:17: runtime error: member access within null pointer of type 'struct lab_data_buffer'
../subprojects/wlroots/types/wlr_buffer.c:51:8: runtime error: member access within null pointer of type 'struct wlr_buffer'
AddressSanitizer:DEADLYSIGNAL
=================================================================
==9716==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000018 (pc 0x556990fcad94 bp 0x7ffe826aab40 sp 0x7ffe826aab20 T0)
==9716==The signal is caused by a READ memory access.
==9716==Hint: address points to the zero page.
    #0 0x556990fcad94 in wlr_buffer_lock ../subprojects/wlroots/types/wlr_buffer.c:51
    #1 0x556990f876d4 in wlr_scene_buffer_create ../subprojects/wlroots/types/scene/wlr_scene.c:361
    #2 0x556990e78ae6 in ssd_update_title ../src/ssd/ssd_titlebar.c:242
    #3 0x556990e74ba5 in ssd_titlebar_create ../src/ssd/ssd_titlebar.c:63
    #4 0x556990e70d17 in ssd_create ../src/ssd/ssd.c:146
    #5 0x556990e479ad in xdg_toplevel_view_map ../src/xdg.c:312
    #6 0x556990e43274 in handle_map ../src/xdg.c:69
    #7 0x556991071fda in wlr_signal_emit_safe ../subprojects/wlroots/util/signal.c:29
    #8 0x556990fbf66c in xdg_surface_role_commit ../subprojects/wlroots/types/xdg_shell/wlr_xdg_surface.c:315
    #9 0x556990fd96fd in surface_commit_state ../subprojects/wlroots/types/wlr_compositor.c:466
    #10 0x556990fda8bb in surface_handle_commit ../subprojects/wlroots/types/wlr_compositor.c:523
    #11 0x7f88aa20fd49  (/usr/lib/libffi.so.8+0x6d49)
    #12 0x7f88aa20f266  (/usr/lib/libffi.so.8+0x6266)
    #13 0x7f88ab87b322  (/usr/lib/libwayland-server.so.0+0xd322)
    #14 0x7f88ab8765cb  (/usr/lib/libwayland-server.so.0+0x85cb)
    #15 0x7f88ab8791c9 in wl_event_loop_dispatch (/usr/lib/libwayland-server.so.0+0xb1c9)
    #16 0x7f88ab876d36 in wl_display_run (/usr/lib/libwayland-server.so.0+0x8d36)
    #17 0x556990e1edc5 in main ../src/main.c:82
    #18 0x7f88aa48530f in __libc_start_call_main (/usr/lib/libc.so.6+0x2d30f)
    #19 0x7f88aa4853c0 in __libc_start_main@GLIBC_2.2.5 (/usr/lib/libc.so.6+0x2d3c0)
    #20 0x556990dfd594 in _start (/home/johan/tmp/labwc-Consolatis/build/labwc+0x48a594)
```

**Comment by johanmalm** [comment]
20220220_21h47m05s_grim

**Comment by Consolatis** [comment]
Alright, as mentioned at IRC I did go through the whole diff again and changed some minor things:
- added one more sanity check to `src/ssd/ssd.c` `ssd_get_part_type()`
- same function got some comments to get a quick grasp of whats going on in that if else construct
- all of the ssd_*_update() functions were turned into a `switch(part->type)` to have the code stuck a bit less together
- SPDX-License-Identifier in .h files apparently have to use `/* this style of comment */` while .c files have to use `// this style`, thus fixed `include/common/scene-helpers.h` and checkpatch is now silent regarding the new files (well, other than for the non-macro).
- removed some more logging
- squashed everything

If you have anything else that should be changed feel free to not pull this just yet but from my side it seems ready.

**Comment by johanmalm** [comment]
Super work!

**Pull request merged**
